name: Release Bat Files

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Zip install.bat
      run: zip install.zip install.bat

    - name: Zip update.bat
      run: zip update.zip update.bat

    - name: Create GitHub Release with assets
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        files: |
          install.zip
          update.zip
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}